[bq.creds]
type = "service_account"
project_id = "emakia"
private_key_id = "236347b5f4b3b12f9677327be1a52701d79c20e0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQDHLwB3Xt7FZWuf
mc52d7H9wq4XWATBI4P7n6GjoyeKwVDGl1h+XHCq3cMymcF4uUx6P6GCzaiFtov6
lWA80yVjTkUCobGwHWiwoN8ahGpR197baRGpNBx/TntxhK8YBuw6Hf5ScQfLwgSX
UGX/WQq8l73rgQ2bnKszFxuKbDE11yf0AhItBZUsxgIslkyYuRv5hdM3W4QOl1Cz
+36XFK9zpDk5bqQyp3bS9uANCLCYUr2LBWi2xB4ofb8ulZHUXOX3REgRwtIF3clK
9IQb4N5Qsvq7zBbdYATxoPr9uBdD9xPkOwsJrC0B3gtkYP9wZBhALJtIW+s4riWh
EIvdeg0RAgMBAAECgf9aKAwt++MZti5gr12kgcku80+ZgV2ljk3PNxIS32amh5no
SdjkWTMmI/qWjMHlwvm629JfQndlDpuNcM9+uJPTvzm9VzL2ZFlemXJirkzxfqSA
663yyIOdnAiD+WrHlVqXc7wJ1N+Set9ZHisMyWDyvDxavK9MID3dgjgVD6O2mkAE
z9MIqC+vIaZr7oDc8X1bkSSbKG8ePDYq6Q9SZfhJCZ/kkA3kK5ghpgiESep+6mUb
Z1dvfqv7UVqTDQFjNBlrvxupsYq3DHVvCejYxgjDnPmaB/jmKXU1AkehldyQsLWe
WzGUbUDTfY7B5T9/PtDOJe6rmaoUu5S44NszxwECgYEA6xwgfLJu0MWMXrcv/sf6
53mgjeUenPlfTCNJQ6ZybEk6TYUl1TAbYTaC3xvSRlekHkpYP4020Xqyzl0O32Ud
QeZO5Gm6eQ25NPDwkfpht0/mfRuRriQAFk5j0Q68rPjQNFWtTuIjoRowh8Gfwfn2
lAMRiV8oO+9pj64N3sQWyIECgYEA2OGvq1xAq+Zima0A18vjz91jeWjFPKKDySEi
ZpzGEifpbe3dOSgpQE02DmKOGzHdiNVrRa+TI06KaBTX/NuYCoXWq+8q96/df62y
jHsewmXS3c6cAZg3GbtWmXf6mknuwidmqLA+E34y4UIz1ZZ6FNWgNNT4ZkF8kIaR
1Gl0fJECgYAY8nEYCi7sBCoy2qlDFaEv8p3wsIEhEuzjvVLG1OCLUPHYy+oJxwMA
u7IDToZvZFlLxYO7qpZIgAZ9Ey7C0Y3bMj7oybc5pRUj4vUD6Fd6BgZk/AnnOnav
5z18L14h1HzzMKwlFKXHMGo53XfAM2/QoMq5ktlIEs1Wq5dZLeFlAQKBgQDUQwWY
E+DjnMaRmwWBLnaXARkTQRwQvQl39qrhfLxKFq/aO/vQreK5oRevuntUWFh2TFIB
0NWTr5G8TfIZ8p16ZwT0H06RPZjuFgTygqlXHyrilQyQbvY2g+g8qXUmPgekE8Xg
gSUwFModNprehriS3YU/T9SQ17TfCiV9m3w7UQKBgFgmqKRC8dmYT90nLCEaBTyi
1rjB6xAHN47Jxgjh4mi6Fxqaxe6/TQ4rGnqgDjObwFZn2e6QcSgmJkMyyw/mANH1
FPuto3GKxTz5uCKcKsLSwzzhk0zheuxwror3igjpi4ZeIQQN8hgiYozu/wD4VO8Y
QzTk/IuN1FmhkswHiHpj
-----END PRIVATE KEY----- """
client_email = "streamlit-bigquery-service@emakia.iam.gserviceaccount.com"
client_id = "114322875175488887385"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-bigquery-service%40emakia.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
